/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package proyectofinalpoo;

import conexion.Conexion;
import java.sql.*;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.ResultSetMetaData;
import java.sql.SQLException;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
/**
 *
 * @author Daniel Medina
 */
public class PanelLibros extends javax.swing.JPanel {

    /**
     * Creates new form PanelLibros
     */
    public PanelLibros() {
        initComponents();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jtfBuscarID = new javax.swing.JTextField();
        btnCargarLib = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        btnEliminar = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jtfIDLib = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jtfNombreLib = new javax.swing.JTextField();
        jtfAutorLib = new javax.swing.JTextField();
        jtfPaginasLib = new javax.swing.JTextField();
        jtfAnioLib = new javax.swing.JTextField();
        jtfEditorialLib = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        btnAgregarLib = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tableLibro = new javax.swing.JTable();

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        jPanel1.setBackground(new java.awt.Color(45, 164, 242));
        jPanel1.setForeground(new java.awt.Color(34, 95, 255));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setText("ID:");

        jtfBuscarID.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jtfBuscarID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtfBuscarIDActionPerformed(evt);
            }
        });

        btnCargarLib.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnCargarLib.setText("Cargar desde BD");
        btnCargarLib.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCargarLibActionPerformed(evt);
            }
        });

        jButton2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton2.setText("Cargar ");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        btnEliminar.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnEliminar.setText("Eliminar");
        btnEliminar.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel2.setText("ID:");

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel3.setText("Nombre:");

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel4.setText("Autor:");

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel5.setText("Editorial:");

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel6.setText("Nro de Páginas:");

        jtfIDLib.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jtfIDLib.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtfIDLibActionPerformed(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel7.setText("Año:");

        jtfNombreLib.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jtfNombreLib.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtfNombreLibActionPerformed(evt);
            }
        });

        jtfAutorLib.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jtfAutorLib.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtfAutorLibActionPerformed(evt);
            }
        });

        jtfPaginasLib.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jtfPaginasLib.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtfPaginasLibActionPerformed(evt);
            }
        });

        jtfAnioLib.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jtfAnioLib.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtfAnioLibActionPerformed(evt);
            }
        });

        jtfEditorialLib.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jtfEditorialLib.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtfEditorialLibActionPerformed(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(0, 0, 102));
        jLabel8.setText("Libreria UCC");
        jLabel8.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        btnAgregarLib.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnAgregarLib.setText("Agregar");
        btnAgregarLib.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnAgregarLib.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarLibActionPerformed(evt);
            }
        });

        tableLibro.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "ID", "Nombre", "Autor", "Editorial", "# de Paginas", "Año", "Disponible"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Integer.class, java.lang.Integer.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                true, false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tableLibro);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                        .addGap(38, 38, 38)
                        .addComponent(jLabel1)
                        .addGap(6, 6, 6)
                        .addComponent(jtfBuscarID, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnCargarLib)))
                .addGap(18, 18, 18))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jtfEditorialLib, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jtfPaginasLib, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jtfAnioLib, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(35, 35, 35)
                        .addComponent(btnAgregarLib)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 41, Short.MAX_VALUE)
                        .addComponent(btnEliminar)
                        .addGap(25, 25, 25))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel8)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jtfIDLib, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel3)
                                .addGap(12, 12, 12)
                                .addComponent(jtfNombreLib, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jtfAutorLib, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jtfIDLib, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4)
                    .addComponent(jtfAutorLib, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jtfNombreLib, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jtfEditorialLib, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6)
                    .addComponent(jtfPaginasLib, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7)
                    .addComponent(jtfAnioLib, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnAgregarLib)
                    .addComponent(btnEliminar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 221, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(7, 7, 7)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jtfBuscarID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton2)
                    .addComponent(btnCargarLib))
                .addGap(49, 49, 49))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jtfBuscarIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtfBuscarIDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtfBuscarIDActionPerformed

    private void btnCargarLibActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCargarLibActionPerformed

        try{
            DefaultTableModel modelo = new DefaultTableModel();
            tableLibro.setModel(modelo);
            
            PreparedStatement ps =null;
            ResultSet rs = null;
            Conexion conn = new Conexion();
            Connection con = conn.getConexion();
            
            String sql = "SELECT id_libro, nombre_l, autor_l, editorial_l, nro_paginas_l, anio_l, disponible_l FROM libros";
            //System.out.println(sql);
            ps = con.prepareStatement(sql);
            rs =ps.executeQuery();
            //Pasando resultado de la consulta
            ResultSetMetaData rsMd = rs.getMetaData();
            
            //Cuantos datos regresa esa consulta
            int cantidadColumnas = rsMd.getColumnCount();
            
            modelo.addColumn("ID");
            modelo.addColumn("Nombre");
            modelo.addColumn("Autor");
            modelo.addColumn("Editorial");
            modelo.addColumn("# de Páginas");
            modelo.addColumn("Año");
            modelo.addColumn("Disponible");
            
            //Recorrer
            while(rs.next()){
            
                Object[] filas = new Object[cantidadColumnas];
                
                for(int i = 0; i<cantidadColumnas;i++){
                    filas[i] = rs.getObject(i+1);
                    
                }
                modelo.addRow(filas);
            }
                     
            
            
        }catch (SQLException ex){
            System.err.println(ex.toString());
        }
    }//GEN-LAST:event_btnCargarLibActionPerformed

    private void jtfIDLibActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtfIDLibActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtfIDLibActionPerformed

    private void jtfNombreLibActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtfNombreLibActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtfNombreLibActionPerformed

    private void jtfAutorLibActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtfAutorLibActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtfAutorLibActionPerformed

    private void jtfPaginasLibActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtfPaginasLibActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtfPaginasLibActionPerformed

    private void jtfAnioLibActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtfAnioLibActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtfAnioLibActionPerformed

    private void jtfEditorialLibActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtfEditorialLibActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtfEditorialLibActionPerformed

    private void btnAgregarLibActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarLibActionPerformed
        Conexion objCon = new Conexion();
        Connection conn = objCon.getConexion();
        DefaultTableModel modelo = new DefaultTableModel();
        PreparedStatement ps = null;
        tableLibro.setModel(modelo);
        String id_producto, disponible;
        
        
        PreparedStatement select = null;
        try{
            /*
            String sqlSelect = "SELECT id_producto FROM reserva WHERE id_producto =" +jtfIDLib.getText();
            
            Statement stmt = conn.createStatement();
            ResultSet result = stmt.executeQuery(sqlSelect);
            
            id_producto = result.getString("id_producto");
            
            if (id_producto==jtfIDLib.getText()){
                disponible = "No";
            }else{
                disponible = "Si";
            }
            */
            disponible = "Si";
            ps = conn.prepareStatement("INSERT INTO libros(id_libro,nombre_l,autor_l,editorial_l,nro_paginas_l,anio_l,disponible_l) "
                    + "VALUES (?,?,?,?,?,?,?)");
            
            ps.setString(1,jtfIDLib.getText());
            ps.setString(2,jtfNombreLib.getText());
            ps.setString(3,jtfAutorLib.getText());
            ps.setString(4,jtfEditorialLib.getText());
            ps.setString(5,jtfPaginasLib.getText());
            ps.setString(6,jtfAnioLib.getText());
            ps.setString(7,disponible);
            
            ps.execute();
            
            JOptionPane.showMessageDialog(null, "Producto guardado con exito");
            Object[] fila = new Object[7];
            fila[0] = jtfIDLib.getText();
            fila[1] = jtfNombreLib.getText();
            fila[2] = jtfAutorLib.getText();
            fila[3] = jtfEditorialLib.getText();
            fila[4] = jtfPaginasLib.getText();
            fila[5] = jtfAnioLib.getText();
            fila[6] = disponible;
            
            modelo.addRow(fila);

        }catch(Exception ex){
            JOptionPane.showMessageDialog(null, "Error al guardar el producto");
            System.out.println(ex);
        }
    }//GEN-LAST:event_btnAgregarLibActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed

        String campo = jtfBuscarID.getText();
        String where = "";
        
        if (!"".equals(campo)){
            where = " WHERE id_libro = '" + campo + "';";
        }
        
        
        try{
            DefaultTableModel modelo = new DefaultTableModel();
            tableLibro.setModel(modelo);
            
            PreparedStatement ps =null;
            ResultSet rs = null;
            Conexion conn = new Conexion();
            Connection con = conn.getConexion();
            
            String sql = "SELECT id_libro, nombre_l, autor_l, editorial_l, nro_paginas_l, anio_l, disponible_l FROM libros " + where;
            //System.out.println(sql);
            ps = con.prepareStatement(sql);
            rs =ps.executeQuery();
            //Pasando resultado de la consulta
            ResultSetMetaData rsMd = rs.getMetaData();
            
            //Cuantos datos regresa esa consulta
            int cantidadColumnas = rsMd.getColumnCount();
            
            modelo.addColumn("ID");
            modelo.addColumn("Nombre");
            modelo.addColumn("Autor");
            modelo.addColumn("Editorial");
            modelo.addColumn("# de Páginas");
            modelo.addColumn("Año");
            modelo.addColumn("Disponible");
            
            //Recorrer
            while(rs.next()){
            
                Object[] filas = new Object[cantidadColumnas];
                
                for(int i = 0; i<cantidadColumnas;i++){
                    filas[i] = rs.getObject(i+1);
                    
                }
                modelo.addRow(filas);
            }
                     
            
            
        }catch (SQLException ex){
            System.err.println(ex.toString());
        }
        
    }//GEN-LAST:event_jButton2ActionPerformed

    private void btnEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarActionPerformed
        DefaultTableModel modelo = new DefaultTableModel();
        tableLibro.setModel(modelo);
        PreparedStatement ps = null;
        
        try{
            
            Conexion objCon = new Conexion();
            Connection conn = objCon.getConexion();
            
            int Fila = tableLibro.getSelectedRow();
            String idLibro = tableLibro.getValueAt(Fila,0).toString();
            
            ps = conn.prepareStatement("DELETE FROM libros WHERE id_libro=?");
            ps.setString(1, idLibro);
            ps.execute();

            modelo.removeRow(Fila);
            
        }catch(SQLException ex){
            System.out.println(ex.toString());
        }
    }//GEN-LAST:event_btnEliminarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAgregarLib;
    private javax.swing.JButton btnCargarLib;
    private javax.swing.JButton btnEliminar;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jtfAnioLib;
    private javax.swing.JTextField jtfAutorLib;
    private javax.swing.JTextField jtfBuscarID;
    private javax.swing.JTextField jtfEditorialLib;
    private javax.swing.JTextField jtfIDLib;
    private javax.swing.JTextField jtfNombreLib;
    private javax.swing.JTextField jtfPaginasLib;
    private javax.swing.JTable tableLibro;
    // End of variables declaration//GEN-END:variables
}
